matrix:
  include:

    # building actual bot server application
    - language: node_js
      secure: "LOFvRZgTz4Js8jS8LvPs9rbEtyy0veIA2XVuuKhi/nWmi9qJ4llhtCjM27Mu8RD0mlv5to3RQHjptc8I+7Iee9N26Rqjps/Jh++ijJbgS45OVkSFq+y6vOy1oD7jj50SjMX8GjOjxc10Y9J2Py09/8eZ3+kUfQ0M6FBx/fFXhfwtY24DusfYTLwbVS/mwHVIbxpxNi1IwdTLFto28pt/fYrhMGNi5f226JoO6oaGniAaVio1A32GqymAjgHfwWvw3on19yO9ZdB/R74CbWPq/Vo+p6a9i1yUnBNLznwAIfXzKRs7iRjYp2Udp6/xhjnVnDp3J/BdyyhcqmKY4tmH1AkHgGWbD+0nuvH+8a60grbkuRpgVpJf4d04R7PgTKqvTSyASOv1k0pKgCGhRje7NykKoFHBOiYF6TwF95FdPMOrgMF5XVPm2Ja0SugRLjuos2bF5F13/++wohYQywJC2izQV72pA5sr3OLA0OfLknHRvrZbCFpAJESt/MT0EvIBwECRgdHSAIBfwg5a7pDfsluMQnypXLsRWMTKnHL22UH0jOO8A0GegUj+FcVPQ7SmkjmJ59FGNmXiMsmTYK5xSN+lpNfyNXt95cWnT9XPAKbHPqq5pp4dIvYLzy/PpPDU1icBT34w04lScE7e+olkbPwlyK+tGGezgnh6T7ilnq0="
      before_install:
        - npm install
      node_js:
        - node
        - lts/*
      script:
        - npm test

    # build WebAPIClient
    - language: csharp
      solution: WebApiClient/YuriClient.sln
